const APP_VERSION='__APP_VERSION__';
const CACHE_PREFIX='go-club-offline-';
const CACHE_NAME=CACHE_PREFIX+APP_VERSION;
const STATUS_URL=new URL('./__offline_status__',self.registration.scope).href;
const INDEX_URL=new URL('./index.html',self.registration.scope).href;
const OFFLINE_URL=new URL('./offline.html',self.registration.scope).href;
async function writeStatus(cache,ready,cachedCount,error){await cache.put(STATUS_URL,new Response(JSON.stringify({ready,version:APP_VERSION,cachedCount,error:error||null}),{headers:{'Content-Type':'application/json'}}));}
async function readStatus(){const cache=await caches.open(CACHE_NAME),response=await cache.match(STATUS_URL);if(!response)return {ready:false,version:APP_VERSION,cachedCount:0};try{return await response.json();}catch{return {ready:false,version:APP_VERSION,cachedCount:0,error:'状态记录损坏。'};}}
async function resourcesFromManifest(){const response=await fetch(new URL('./offline-assets.json',self.registration.scope),{cache:'no-store'});if(!response.ok)throw new Error('离线资源清单不可读取。');const value=await response.json();if(value.version!==APP_VERSION||!Array.isArray(value.resources))throw new Error('离线资源清单版本不一致。');return value.resources;}
async function prepare(resources){const cache=await caches.open(CACHE_NAME),urls=[...new Set(resources.map(path=>new URL(path,self.registration.scope).href))];try{for(const url of urls){const response=await fetch(url,{cache:'reload'});if(!response.ok)throw new Error(`${new URL(url).pathname} 返回 ${response.status}`);await cache.put(url,response);}await writeStatus(cache,true,urls.length);return {ok:true,version:APP_VERSION,cachedCount:urls.length};}catch(error){await writeStatus(cache,false,0,error instanceof Error?error.message:'缓存失败');return {ok:false,version:APP_VERSION,cachedCount:0,error:error instanceof Error?error.message:'缓存失败'};}}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);try{const response=await fetch(OFFLINE_URL,{cache:'reload'});if(response.ok)await cache.put(OFFLINE_URL,response);}catch{}try{await prepare(await resourcesFromManifest());}catch(error){await writeStatus(cache,false,0,error instanceof Error?error.message:'首次缓存失败');}})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME)await caches.delete(key);await self.clients.claim();})());});
self.addEventListener('message',event=>{const reply=value=>event.ports[0]?.postMessage(value);if(event.data?.type==='GET_STATUS'){event.waitUntil(readStatus().then(value=>reply({type:'OFFLINE_STATUS',...value})));}else if(event.data?.type==='PREPARE_OFFLINE'){event.waitUntil(prepare(Array.isArray(event.data.resources)?event.data.resources:[]).then(value=>reply({type:'PREPARE_RESULT',...value})));}else if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET'||new URL(request.url).origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith((async()=>{const status=await readStatus(),cache=await caches.open(CACHE_NAME);if(status.ready){const cached=await cache.match(INDEX_URL,{ignoreVary:true});if(cached)return cached;}try{return await fetch(request);}catch{return (await cache.match(OFFLINE_URL,{ignoreVary:true}))||new Response('离线资源尚未准备。',{status:503});}})());return;}event.respondWith((async()=>{const cached=await caches.match(request.url,{ignoreVary:true});if(cached)return cached;return fetch(request);})());});
